adapter:
  image: node:10
  volumes:
    - $PWD:/home/node
  links:
    - mongo
  environment:
    - WATERLINE_ADAPTER_TESTS_DATABASE=sails-mongo
    - WATERLINE_ADAPTER_TESTS_URL=mongo/testdb
    - WATERLINE_ADAPTER_TESTS_HOST=mongo
    - NODE_ENV=test
  user: node
  working_dir: /home/node
  command:
    - bash -c "npm test"

mongo:
  image: mongo:4
  restart: always
  command: "--smallfiles --logpath=/dev/null"
  ports:
    - "27017:27017"
