adapter:
  image: node:8
  volumes:
    - $PWD:/home/node
  links:
    - mongo
  environment:
    - WATERLINE_ADAPTER_TESTS_DATABASE=sails-mongo
    - WATERLINE_ADAPTER_TESTS_URL=mongo/testdb
    - WATERLINE_ADAPTER_TESTS_HOST=mongo
    - NODE_ENV=test
  command:
    - bash -c "cd /home/node && npm test"

mongo:
  image: mongo:4
  restart: always
  command: "--smallfiles --logpath=/dev/null"
  ports:
    - "27017:27017"
